Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,9 +28,8 @@ jobs:
         if: matrix.browser == 'chrome'
         run: |
           sudo apt-get update
-          sudo apt-get install -y google-chrome-stable
-          echo "Installed Chrome version:"
-          google-chrome --version || true
+          sudo apt-get install -y google-chrome-stable || echo "Error installing Chrome"
+          google-chrome --version || echo "Chrome not found"
 
       - name: Install ChromeDriver
         if: matrix.browser == 'chrome'
@@ -42,21 +41,21 @@ jobs:
           sudo mv chromedriver /usr/local/bin/
 
       # Configuración de Firefox
+      - name: Install Firefox
+        if: matrix.browser == 'firefox'
+        run: |
+          wget -q "https://ftp.mozilla.org/pub/firefox/releases/132.0/linux-x86_64/en-US/firefox-132.0.tar.bz2" -O firefox.tar.bz2
+          tar -xjf firefox.tar.bz2
+          sudo mv firefox /opt/firefox
+          sudo ln -sf /opt/firefox/firefox /usr/bin/firefox
+          firefox --version || echo "Firefox installation failed"
+
       - name: Install GeckoDriver
         if: matrix.browser == 'firefox'
         run: |
           wget https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
           tar -xvzf geckodriver-v0.35.0-linux64.tar.gz
           sudo mv geckodriver /usr/local/bin/
-
-      - name: Install Firefox
-        if: matrix.browser == 'firefox'
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y software-properties-common
-          sudo add-apt-repository -y ppa:mozillateam/ppa
-          sudo apt-get update
-          sudo apt-get install -y firefox
 
       - name: Build and Test
         run: mvn clean test -Dbrowser=${{ matrix.browser }}
